#### **Homework 01:**
Generate random matrix of size 10 x 5. Then, solve the following problems:

In [ ]:
import numpy as np

In [ ]:
a = np.random.random((10,5))
print (a)

[[0.00147555 0.24111778 0.62030405 0.13981803 0.46061029]
 [0.53247527 0.85641942 0.81915142 0.28510063 0.05321843]
 [0.33627008 0.8205094  0.45157069 0.50557413 0.37049083]
 [0.31791773 0.75437541 0.30693097 0.57656872 0.39171731]
 [0.50068973 0.50788233 0.20342747 0.04115277 0.40313017]
 [0.63820777 0.55651696 0.74945506 0.44434938 0.10023916]
 [0.76812182 0.58956668 0.45558538 0.90899709 0.73561137]
 [0.79830291 0.68775665 0.45881323 0.77314554 0.07536066]
 [0.66853985 0.23323604 0.465036   0.8201856  0.75865531]
 [0.7886091  0.27992028 0.41027969 0.46511743 0.05164558]]


##### **Problem 01:**
Calculate the sum and mean of the 2nd row of the matrix.

In [ ]:
row_mean = np.mean(a, axis=1)
sum_mean = np.sum(a, axis=1) 
row2_mean = row_mean[1]
row2_sum = sum_mean[1]
print("Mean of Row 2 is", row2_mean)
print("Sum of Row2 is" , row2_sum)

Mean of Row 2 is 0.5092730351424267
Sum of Row2 is 2.5463651757121335


##### **Problem 02:**
Find the sum and mean of all the rows of the matrix.

In [ ]:
sum = np.sum (a)
print (sum)
mean = np.mean (a)
print (mean)

24.179153178453497
0.48358306356906994


##### **Problem 03:**
Find the mean of the 3rd column of the matrix without using the built-in function and loop.

In [ ]:
coloumn_mean = np.mean(a, axis=0)
coloumn3 = coloumn_mean[2]
print (coloumn3)



0.49405539683622707


##### **Problem 04:**
Generate the vector `[25, 16, 9, 4, 1]` and then find the square root of each element of the vector using for loop. **Hint:** Use `np.sqrt()` function to find the square root of a number, don't use any other built-in function.

In [ ]:
b = np.arange(6)**2
res = b[:0:-1]
print (res)
np.sqrt(res)

[25 16  9  4  1]


array([5., 4., 3., 2., 1.])

##### **Problem 05:**
Write a function that takes a number and returns a vector like the previous problem. For example, if the input is 5, then the output should be `[25, 16, 9, 4, 1]`. If the input is 10, then the output should be `[100, 81, 64, 49, 36, 25, 16, 9, 4, 1]`.

In [ ]:
c = np.arange(11)**2

res = c[:0:-1]
print (res)

[100  81  64  49  36  25  16   9   4   1]


##### **Problem 06:**
Generate the following block matrix:

$$
\begin{bmatrix}
1 & 0 & 0 & 2 & 2 \\
0 & 1 & 0 & 2 & 2 \\
0 & 0 & 1 & 2 & 2 \\
25 & 16 & 9 & 4 & 1 \\
\end{bmatrix}
$$

You can use any built-in function to generate the matrix.

In [ ]:
import numpy as np 


b = np.array([[1,0,0,2,2], 
[0,1,0,2,2],
[0,0,1,2,2],
[25,16,9,4,1]]) 
for row in b:
  for col in row:
    print(col, end=' ')
  print()

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

##### **Problem 07:**
Plot $y = 2x^2 + 3x + 1$ for $x \in [-3, 3]$ with interval 0.25. You can use any built-in function to plot the graph.

In [ ]:
# Write your code here

##### **Problem 08:**
Plot $x + y + z = 1$ for $x, y \in [-3, 3]$ with interval 0.5. Use meshgrid to generate the grid. You can use any built-in function to plot the surface.

In [ ]:
# Write your code here

##### **Problem 09:**
Download the image of Lena Forsen from the following link: [https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png](https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png). Then, do the following tasks:

*  Load the image to a numpy array.
*  Find the size of the image.
*  Find the minimum and maximum value of the image.
*  Find the mean and standard deviation of the image.
*  Plot the image using `plt.imshow()` or `display()`.
*  Resize the image to 50 x 50.
*  Convert the image to grayscale.
*  Plot the grayscale image using `plt.imshow()` or `display()`.
*  Save the grayscale image using `imsave()`.
*  Stack the columns of the image to form a vector of size 2500 x 1.

In [ ]:
# Write your code here